/* Version en ligne : les fichiers restent dans les vrais dossiers du Master HES-SO. */
const MODULE_FOLDERS=['01_FTP_Physics','02_MA_HYBRD','03_FTP_ModSim','04_FTP_Multiphy','05_CM_QRM-A','06_FTP_OrdDiff-A','07_TSM_FMechHeat','08_TSM_CSM-A','09_CM_AdvProjMgmt','10_FTP_CompAlg','11_MA_CFD'];
const MASTER_SECTIONS=[['cours','Cours','01_Cours'],['exercices','Exercices','02_Exercices'],['projets','Projets','03_Projets'],['resumes','Résumés','04_Resumes']];
let onlineBaseId,onlineCourseId,onlineSectionId,onlineCourseIndex=-1,onlineSection='cours';

driveState=function(text,on=false){driveStatus.textContent=text;driveBadge.textContent=on?'SYNCHRONISÉ':'NON CONNECTÉ';driveBadge.classList.toggle('synced',on)};
async function rootFromPath(parts){const path=parts.map(encodeURIComponent).join('/');const response=await fetch('https://graph.microsoft.com/v1.0/me/drive/root:/'+path,{headers:{Authorization:'Bearer '+await token(true)}});if(response.status===404)return null;if(!response.ok)throw Error('OneDrive a répondu '+response.status+'.');return await response.json()}
async function onlineRoot(){if(onlineBaseId)return onlineBaseId;for(const candidate of [['HES-SO-Master','semestre 1'],['semestre 1']]){const item=await rootFromPath(candidate);if(item){onlineBaseId=item.id;return onlineBaseId}}throw Error('Dossier « HES-SO-Master / semestre 1 » introuvable dans ce OneDrive.');}
async function child(parentId,name){const data=await(await graph('/me/drive/items/'+parentId+'/children?$select=id,name,folder')).json();return data.value.find(item=>item.folder&&item.name===name)}
folder=async function(){if(onlineSectionId&&onlineCourseIndex===selected)return onlineSectionId;const base=await onlineRoot();const course=await child(base,MODULE_FOLDERS[selected]);if(!course)throw Error('Dossier du cours '+modules[selected]+' introuvable.');const section=MASTER_SECTIONS.find(item=>item[0]===onlineSection);const folderItem=await child(course.id,section[2]);if(!folderItem)throw Error('Dossier « '+section[1]+' » introuvable.');onlineCourseId=course.id;onlineSectionId=folderItem.id;onlineCourseIndex=selected;return onlineSectionId};
function folderTabs(){return '<div class="folder-tabs">'+MASTER_SECTIONS.map(item=>'<button class="folder-tab '+(item[0]===onlineSection?'active':'')+'" data-online-section="'+item[0]+'">'+item[1]+'</button>').join('')+'</div>'}
async function nestedFiles(parentId,prefix=''){const data=await(await graph('/me/drive/items/'+parentId+'/children?$select=id,name,size,lastModifiedDateTime,file,folder,eTag,webUrl&$orderby=lastModifiedDateTime%20desc')).json(),files=[];for(const item of data.value){if(item.folder)files.push(...await nestedFiles(item.id,prefix+item.name+' / '));else if(item.file)files.push({...item,name:prefix+item.name})}return files}
listFiles=async function(){driveFiles.classList.remove('hidden');driveFiles.innerHTML=folderTabs()+'<p class="empty">Chargement de tous les sous-dossiers…</p>';try{const folderId=await folder(),files=await nestedFiles(folderId);driveFiles.innerHTML=folderTabs()+(files.length?files.map((file,index)=>'<button class="drive-file" data-online-file="'+index+'"><b>'+escape(file.name)+'</b><small>'+Math.ceil(file.size/1024)+' Ko · '+new Date(file.lastModifiedDateTime).toLocaleDateString('fr-CH')+'</small></button>').join(''):'<p class="empty">Aucun fichier dans « '+MASTER_SECTIONS.find(item=>item[0]===onlineSection)[1]+' ».</p>');driveFiles.querySelectorAll('[data-online-section]').forEach(button=>button.onclick=()=>{onlineSection=button.dataset.onlineSection;onlineSectionId=null;listFiles()});driveFiles.querySelectorAll('[data-online-file]').forEach(button=>{const file=files[+button.dataset.onlineFile];button.onclick=()=>/\.pdf$/i.test(file.name)?openFile(file):window.open(file.webUrl||'https://www.office.com/','_blank','noopener')});driveState('Synchronisé avec '+modules[selected]+' · '+MASTER_SECTIONS.find(item=>item[0]===onlineSection)[1]+'.',true)}catch(error){driveFiles.innerHTML=folderTabs()+'<p class="empty">'+escape(error.message)+'</p>';driveState(error.message)}};
async function selectHesAccount(){const client=await init();const saved=client.getAllAccounts();const hesAccount=saved.find(item=>/@hes-so\.ch$/i.test(item.username||''));if(hesAccount){account=hesAccount;return}if(!/@hes-so\.ch$/i.test((account&&account.username)||''))account=null}
/* La redirection évite l’erreur MSAL « block_nested_popups » sur mobile et dans l’application. */
token=async function(interactive=false){const client=await init();if(!account){if(!interactive)throw Error('Connecte ton compte HES-SO.');sessionStorage.setItem('mse.pending-connect','1');await client.loginRedirect({scopes:SCOPES,prompt:'select_account'});return null}try{return(await client.acquireTokenSilent({account,scopes:SCOPES})).accessToken}catch(error){if(!interactive)throw error;sessionStorage.setItem('mse.pending-connect','1');await client.acquireTokenRedirect({account,scopes:SCOPES});return null}};
connect=async function(){connectDrive.disabled=true;connectDrive.textContent='Connexion…';try{await selectHesAccount();await token(true);onlineSectionId=null;onlineCourseIndex=-1;driveTitle.textContent='Documents · '+modules[selected];connectDrive.textContent='Actualiser';await listFiles()}catch(error){driveState(error.message)}finally{connectDrive.disabled=false;if(connectDrive.textContent==='Connexion…')connectDrive.textContent='Connecter mes PDF'}};
upload=async function(files){const pdfs=[...files].filter(file=>file.type==='application/pdf'||/\.pdf$/i.test(file.name));if(!pdfs.length){pdfMessage.textContent='Choisis un fichier PDF.';return}try{const destination=await folder();for(const file of pdfs){pdfMessage.textContent='Envoi de '+file.name+'…';const item=await(await graph('/me/drive/items/'+destination+':/'+encodeURIComponent(file.name)+':/content?@microsoft.graph.conflictBehavior=rename',{method:'PUT',headers:{'Content-Type':'application/pdf'},body:file})).json();await openFile(item)}await listFiles();pdfMessage.textContent='PDF synchronisé avec OneDrive.'}catch(error){pdfMessage.textContent=error.message}};
if(!LOCAL_MODE){connectDrive.onclick=connect;setTimeout(()=>{onlineSectionId=null;onlineCourseIndex=-1;if(account&&/@hes-so\.ch$/i.test(account.username||''))connect()},0)}
if(!LOCAL_MODE) setTimeout(()=>init().then(()=>{if(account&&/@hes-so\.ch$/i.test(account.username||''))connect()}).catch(()=>{}),0);
